version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
