name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    strategy:
      matrix:
        ruby:
          - "3.0"
          - "3.1"
          - "3.2"
        host:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.host }}

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 2
      - name: build
        run: bundle exec rake compile
      - name: test
        run: bundle exec rake

  all-tests-pass:
    if: always()

    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - name: check test jobs
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
