name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: setup
        run: |
          gem install bundler
          bundle install
      - name: build
        run: bundle exec rake compile
      - name: test
        run: bundle exec rake
