on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  create-release:
    name: create GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'rc') }}

  rubygems:
    name: publish to RubyGems
    runs-on: ubuntu-latest

    steps:
      - name: push to RubyGems
        run: |
          gem build lzfse.gemspec
          gem push lzfse-*.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
